import pytest

from tests.test_api import (
    _slow_case_app_security_headers_are_present_on_api_responses,
    _slow_case_async_job_allowed_with_explicit_unsafe_override,
    _slow_case_health_deep_is_dependency_truth_while_health_stays_lightweight,
    _slow_case_lightweight_health_cloud_only_mode_requires_cloud,
    _slow_case_lightweight_health_degrades_when_key_status_empty,
    _slow_case_lightweight_health_includes_external_dependency_note,
    _slow_case_lightweight_health_marks_ollama_primary_prewarm_failure_as_degraded,
    _slow_case_lightweight_health_ollama_first_degrades_when_primary_unavailable_but_fallback_ok,
)


@pytest.mark.asyncio
async def test_app_security_headers_are_present_on_api_responses():
    await _slow_case_app_security_headers_are_present_on_api_responses()


@pytest.mark.asyncio
async def test_async_job_allowed_with_explicit_unsafe_override(monkeypatch):
    await _slow_case_async_job_allowed_with_explicit_unsafe_override(monkeypatch)


@pytest.mark.asyncio
async def test_lightweight_health_includes_external_dependency_note():
    await _slow_case_lightweight_health_includes_external_dependency_note()


@pytest.mark.asyncio
async def test_health_deep_is_dependency_truth_while_health_stays_lightweight(monkeypatch):
    await _slow_case_health_deep_is_dependency_truth_while_health_stays_lightweight(monkeypatch)


@pytest.mark.asyncio
async def test_lightweight_health_cloud_only_mode_requires_cloud(monkeypatch):
    await _slow_case_lightweight_health_cloud_only_mode_requires_cloud(monkeypatch)


@pytest.mark.asyncio
async def test_lightweight_health_ollama_first_degrades_when_primary_unavailable_but_fallback_ok(monkeypatch):
    await _slow_case_lightweight_health_ollama_first_degrades_when_primary_unavailable_but_fallback_ok(monkeypatch)


@pytest.mark.asyncio
async def test_lightweight_health_marks_ollama_primary_prewarm_failure_as_degraded(monkeypatch):
    await _slow_case_lightweight_health_marks_ollama_primary_prewarm_failure_as_degraded(monkeypatch)


@pytest.mark.asyncio
async def test_lightweight_health_degrades_when_key_status_empty(monkeypatch):
    await _slow_case_lightweight_health_degrades_when_key_status_empty(monkeypatch)
